### ISSUE TITLE
Fails to compile GUI on Ubuntu 20.04 for version 1.2.11

### ISSUE THREAD

**Issue by foomip** [HDDcoin-Network/hddcoin-blockchain#14]
install-gui.sh fails with the following output:
```
~/hddcoin-blockchain$ sh install-gui.sh
apt-get is /usr/bin/apt-get
Reading package lists... Done
Building dependency tree
Reading state information... Done
libxss1 is already the newest version (1:1.2.3-1).
nodejs is already the newest version (10.19.0~dfsg-3ubuntu1).
npm is already the newest version (6.14.4+ds-1ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

Installing on Ubuntu 20.04 LTS or newer: Using installed node.js version.
Running git submodule update --init --recursive.

Running git submodule update.

npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!

> yarn@1.22.11 preinstall /home/foomip/hddcoin-blockchain/hddcoin-blockchain-gui/node_modules/yarn
> :; (node ./preinstall.js > /dev/null 2>&1 || true)


> lzma-native@8.0.1 install /home/foomip/hddcoin-blockchain/hddcoin-blockchain-gui/node_modules/lzma-native
> node-gyp-build


> electron-winstaller@5.0.0 install /home/foomip/hddcoin-blockchain/hddcoin-blockchain-gui/node_modules/electron-winstaller
> node ./script/select-7z-arch.js

Selecting 7-Zip for arch x64

> node-pty@0.10.1 install /home/foomip/hddcoin-blockchain/hddcoin-blockchain-gui/node_modules/node-pty
> node scripts/install.js

Traceback (most recent call last):
  File "/usr/share/nodejs/node-gyp/gyp/gyp_main.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/foomip/hddcoin-blockchain/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3252, in <module>
    def _initialize_master_working_set():
  File "/home/foomip/hddcoin-blockchain/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/home/foomip/hddcoin-blockchain/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/foomip/hddcoin-blockchain/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/home/foomip/hddcoin-blockchain/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/foomip/hddcoin-blockchain/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'gyp==0.1' distribution was not found and is required by the application
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/nodejs/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.4.0-92-generic
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/foomip/hddcoin-blockchain/hddcoin-blockchain-gui/node_modules/node-pty
gyp ERR! node -v v10.19.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty@0.10.1 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-pty@0.10.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/foomip/.npm/_logs/2022-01-07T19_52_31_749Z-debug.log
```

install.sh and `. ./activate` work correctly.

**Comment by Zyzonix** [comment]
Same problem here
